<p style="font-family: Arial; font-size:3.75em;color:purple; font-style:bold"><br>
Sudoku
</p><br>

<img src="https://automatetheboringstuff.com/images/000037.jpg">

### Import or create grid

In [1]:
import pandas as pd

In [2]:
#By default, the grid is converted to a table.
dict_grid={
    'A':[5,6,'',8,4,7,'','',''],
    'B':[3,'',9,'','','',6,'',''],
    'C':['','',8,'','','','','',''],
    'D':['',1,'','',8,'','',4,''],
    'E':[7,9,'',6,'',2,'',1,8],
    'F':['',5,'','',3,'','',9,''],
    'G':['','','','','','',2,'',''],
    'H':['','',6,'','','',8,'',7],
    'I':['','','',3,1,6,'',5,9]
    
}
grid=pd.DataFrame(data=dict_grid)
grid

   A  B  C  D  E  F  G  H  I
0  5  3        7
1  6        1  9  5
2     9  8              6
3  8           6           3
4  4        8     3        1
5  7           2           6
6     6              2  8
7           4  1  9        5
8              8        7  9

In [3]:
#Alternative: open other grids from csv files
grid1=pd.read_csv('sudoku_false.csv',index_col=0)
grid1=grid1.apply(pd.to_numeric).fillna('')
grid1

   0  1  2  3  4  5  6  7  8
0     4     2     1     6
1
2  9     5           3     7
3
4  5     7     8     1     4
5     1                 9
6        1           6
7           7     5
8  6     8  9     4  5     3

### Define variables for the 3x3 blocks
<p>Insert into a function: to be recalculated every time a new value is entered in the grid</p>

In [4]:
#example:
upper_left=grid.iloc[:3,:3]
#the subgrids will be numbered from 0 to 8, from top-left to bottom-right. upper_left corresponds to sub_grids[0]
#remove the empty cells, we need blocks only to generate a set of digits.
def content_blocks(grid):
    '''returns a list of list of contents of each block'''
    blocks=[]
    #your code
    return blocks

### Define a class Cell with a value and block number

In [ ]:
class Cell():
    def __init__(self, grid, x, y):
    '''grid is a pd.dataFrame
    x and y are integers within 0 and 8'''
    #define the propertie of cells
    def find_block(self):
    '''find to which block a cell belongs (returns the block number)'''

### Algorithms
[Reference](https://www.kristanix.com/sudokuepic/sudoku-solving-techniques.php)
- 1 <strong>Sole candidate</strong>: cells that can only be filled by one digit (in a row + column + block)
- 2 <strong>Unique candidate</strong>: the cell has several options but is the only one in the row/column/block to have one digit as an option
- 3 <strong>Block and column/row interaction</strong>: if a digit can only be on 1 row or column on a block then we can eliminate it from the possibilities of the other blocks for that row or column.
- 4 <strong>Block/block interaction</strong>: if on 2 aligned blocks a digit can be in only 2 rows then we can eliminate it from these two rows on the third block
- 5 <strong>Naked subset</strong>: when 2 cells in a row/column/block are the only ones to admit the same only two digits, even if these digits are a possibility on other cells (so they can be removed from the options for these other cells, and the list of options for the 2 cells are reduced to these digits only)
- 6 <strong>X-Wing</strong>: look at cells disposed at corners of a rectangle of any size (each corner in a different block): if one digit is an option in each corner cell (and also on their respective rows (or columns)), and if in addition the digit can only be in one of the corners on each side of the rectangle: then the digit can only be in the corner and can be removed from the options for other cells in the rectangle. More generally, <strong>swordfish</strong>: when candidate cells for a specific digit happen to allow for this option on separate rows or columns, but specifically 2 times on each row & 2 times on each column; and at the same time the digit is an option only in all of the rows (or all of the columns). Then it can be removed from all the columns (or rows). To recognize this pattern, see if it is possible to loop (using only vertical or horizontal lines) between all the cells containing a candidate number.
- 7 <strong>Forcing chain</strong>: guess an option for a cell and write down how it would affect other cells. Then guess another option and see if other cells would resolve in the same digit anyway.

In [6]:
def sole_candidate(grid,cell,xargs):
    '''solves for one cell'''

In [7]:
def solve(grid):
    '''solves for the grid'''
    #your code
    while filled<81:
        #your code
        for row in range(0,9):
            for col in range(0,9):
                #your code
                if cell.value=='':
                    result=sole_candidate(grid,cell,xargs)                    
        filled=len(list(filter(None,grid.values.flatten())))
        print(filled)
    return grid